Clean up latest episodes on homepage
JupiterBroadcasting/jupiterbroadcasting.com pull request #236
Opened 2022-08-06 19:28 UTC by reesericci

- replace JB menu item with svg nameplate
- clean up latest episodes

I removed pagination from latest episodes, as it shouldn't be an ever-expanding list of episodes - that belongs to an "All Shows" page. Following in line with that, I shortened the amount of episodes shown on the homepage from 15 to 6.

2022-08-06 23:15 UTC, graemearthur commented
Think this would work with a more episodes link at the end for those who are looking for all episodes

2022-08-07 02:26 UTC, gerbrent commented
Well, you see, this was specifically a feature request I made several weeks ago when the home page was instead the entire JB catalogue - to show many recent episodes, but not all, and w natural pagination.

#### My perspective and thus motivation for that ask is this:

* a new-to-JB listener will likely arrive at the first page, and be in the mood to explore. That can be done either by browsing the menu and sub-menus, or by scrolling. On mobile, scrolling down a page or two is a very intuitive action, and you thus get a good sense of JB's recent offering with more than 6 recent episodes on offer. 
* A seasoned JB listener will know there are several shows, and can either dig into the menu for the specific show they're after, or more often than not browse the last few episodes on offer. 
* If you are a casual JB listener (in contrast to a listen-to-everything type listener) and thus haven't listened in some time, exploring recent topics across all shows is a great way to re-engage said listener.
* with such a small recent-episodes offering on the front page, I get a small sense that perhaps this subset is the only offering on hand. It confuses the "Shows Carousel" with the "Recent Episodes" view, as they have the same artwork, similar shapes, similar number of items. The distinction between both feels obscured at that point in my opinion.

#### scenarios in which 6 or less is not ideal:

With only 6 recent episodes shown, there are regular sub-optimal scenarios where a show is not present on the home page, despite having a relatively recent episode:
* LAN251, Coder476, LUP468, Office8, LAN250, Coder475 - Where's the latest SSH?
* Office 9, LAN252, Coder477, LUP469, SSH76, LAN251 - Only one LUP present, our biggest show?

#### Alternatives
I would welcome discussion and perspective around alternatives - a `more` button might just be the right touch - however I do not believe the above commits and sample without pagination or `more` button is the answer.

Another consideration: A `more` button would thus require an "All Shows" page, which is discussed and strategy not yet decided in #162

2022-08-07 02:26 UTC, gerbrent commented
In conclusion, I do not feel this should be merged until more discussion can happen and a decision be made on approach.

2022-08-18 12:26 UTC, reesericci commented
Could we increase the count of episodes from 6 to 9?

—reese

On August 18, 2022, Bananaman ***@***.***> wrote:
> In my opinion this should not be merged for the reasons you stated
> above @gerbrent <https://github.com/gerbrent>. Tbh I'd close this PR
> too as noone else seems to have strong opinions in the opposite
> direction.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/pull/236#issuecomment-
1219419301>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AEVOPDVTTVRRDAZKN6XVOI3VZYSOJANCNFSM55ZGYP6A>.
You are receiving this because you authored the thread.Message ID:
***@***.***>

2022-08-18 15:22 UTC, gerbrent commented
@reesericci: @ChrisLAS was interested in the same, though i think we should keep pagination...

2022-08-18 16:50 UTC, reesericci commented
I think pagination _is_ hurting the design because "Latest Episodes" shouldn't be an ever-flowing stream of content & makes the design less elegant imo.

2022-08-18 18:36 UTC, ironicbadger commented
Your opinion is noted. Thank you!

2022-08-18 18:55 UTC, reesericci commented
Is that supposed to be passive-agressive?

—reese

On August 18, 2022, Bananaman ***@***.***> wrote:
> Your opinion is noted. Thank you!
>

—
Reply to this email directly, view it on GitHub
<https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/pull/236#issuecomment-
1219811102>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AEVOPDSQ6X3VCXK4MIUOG4DVZZ7EVANCNFSM55ZGYP6A>.
You are receiving this because you were mentioned.Message ID:
***@***.***>

2022-08-18 19:07 UTC, gerbrent commented
> I think pagination _is_ hurting the design because "Latest Episodes" shouldn't be an ever-flowing stream of content & makes the design less elegant imo.

I feel like a "more" button that links to a (currently non-existent) `All Episodes, sorted by latest` page would be a really happy solution to this (and potentially to partially #162 aswell). Though it can be said that it's a small detail for Milestone 1.0, and our collective efforts are likely better spent elsewhere on more pressing and essential tasks.

2022-08-18 19:10 UTC, gerbrent commented
https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/pull/236#issuecomment-1207317664

see here also as a reminder of all my particular reasoning behind the above.

2022-08-18 19:17 UTC, ironicbadger commented
> Is that supposed to be passive-agressive? —reese

Not at all :) Just wanted to let you know that you've been heard even if we don't go with your suggestion.

2022-08-18 23:19 UTC, reesericci commented
Just changed from 15 to 9 and resolved merge conflicts!

2022-08-25 04:34 UTC, gerbrent requested changes

2022-08-25 04:34 UTC, gerbrent commented on themes/jb/layouts/index.html
We would like to keep the pagination. Could you keep this section please?

2022-08-25 04:34 UTC, gerbrent commented on themes/jb/layouts/index.html
```suggestion
    <div class="container">
          {{ partial "helper/pagination.html" . }}
    </div>
```

2022-08-25 04:53 UTC, reesericci commented
Ok just implement your changes!

2022-08-25 05:23 UTC, gerbrent approved these changes

2022-08-25 06:23 UTC, gerbrent approved these changes
Tested and all is perfect! Thanks @reesericci !

2022-08-25 06:23 UTC, merged