Render Full Contact Form even when there are Validation Errors
JupiterBroadcasting/jupiterbroadcasting.com pull request #446
Opened 2022-10-06 14:02 UTC by CGBassPlayer

Fixes #437

* Increase size of contact form iframe to show submit button even when there are validation errors in the form
![contact form with errors](https://user-images.githubusercontent.com/34293941/194333203-f0a1fbd2-a296-47b2-820c-3e02a964b99f.png)

TODO
* Implement test to check if the submit button is within the bounds of the iframe

2022-10-07 21:54 UTC, gerbrent commented
amazing @CGBassPlayer - you're on :fire lately!

2022-10-09 00:30 UTC, elreydetoda requested changes
This is awesome @CGBassPlayer!

You really did an amazing job figuring out how to determine if the button was off the screen or not! I thought you'd be able to do something like `.is_visible()` on a locator, but for some reason playwright isn't like that (it says it's visible in the iframe even when it's not :disappointed: ).

I don't know if that's a bug or something, but the way you're comparing the height of the iframe to the bottom of the button was ingenious! 

Just have a few suggestions to help tidy up the code a bit :slightly_smiling_face: 

Overall though, amazing job!!! :partying_face: :tada: :rocket:

2022-10-09 00:34 UTC, gerbrent commented
nice work both of you! It's a joy just to watch this evolve..

2022-10-09 00:40 UTC, elreydetoda commented
BTW, these are the screenshots getting captured:

![image](https://user-images.githubusercontent.com/10230166/194732327-3e884cf3-784b-4204-ba71-2c632f385a9d.png)

![image](https://user-images.githubusercontent.com/10230166/194732329-8355bcc4-b7e1-4481-9b70-6dac486737e9.png)

2022-10-09 00:48 UTC, CGBassPlayer commented
> I thought you'd be able to do something like `.is_visible()` on a locator, but for some reason playwright isn't like that (it says it's visible in the iframe even when it's not disappointed ).
>
> I don't know if that's a bug or something...

The `.is_visible()` is checking to see if an html element has hidden (ethier `display: none` or `visibility:hidden`) in any of its styling. So even if you can't see physically see it, it is still "visible" on the page
https://playwright.dev/python/docs/actionability#visible

> ...but the way you're comparing the height of the iframe to the bottom of the button was ingenious!
>
> Just have a few suggestions to help tidy up the code a bit :slightly_smiling_face:

Thank you so much @elreydetoda! This is actually my first ever test (my day job does not have a good way to handle anything other than manual testing :cry:) so I will look over what you suggested and update this PR

2022-10-09 00:59 UTC, CGBassPlayer commented on test/e2e/test_contact.py
> +    time.sleep(1) # Give time to scroll to the top
I feel like there isn't a "*best way*" to handle this in playwright yet. I knew my solution would not work if we made the page more than 180px taller. My only concern with this solution is there is padding above the content on the page (room for the navbar), so I am not 100% sure that test would scroll completely to the top. Like would it accept the `h1` being behind the navbar as "in view"?

Given that the navbar padding is only 64 pixels, I think we will be fine for right now, but we should definitely keep an eye out for something that would force playwright to move back to the top of a page.

2022-10-09 01:00 UTC, CGBassPlayer commented on test/e2e/test_contact.py
> +    frame_height: float = float(page.get_attribute(selector="#contact-frame", name="height")) + page.locator(selector="#contact-frame").bounding_box().get("y")
I agree that looks cleaner and easier to read

2022-10-09 01:03 UTC, CGBassPlayer commented on test/e2e/test_contact.py
> +        assert False, "Submit Button is hidden"
I will throw in a brief explanation

2022-10-09 01:42 UTC, elreydetoda commented on test/e2e/test_contact.py
> +    time.sleep(1) # Give time to scroll to the top
So, in my testing locally it seemed like it goes all the way to the top even past the Contact header. You can launch playwright in debug mode (don't currently have this enabled in the container version (i.e. `make tests`) but if you've got it installed with pipenv then you can do this) by doing something like: `PWDEBUG=1 pytest --base-url http://localhost:1313` which'll give you the interface you see below.

[contact-test_scroll.webm](https://user-images.githubusercontent.com/10230166/194733610-2ff202cf-ebb2-4e82-9120-6c1d900fef27.webm)

2022-10-09 01:45 UTC, merged

2022-10-09 01:46 UTC, elreydetoda commented
> > ...but the way you're comparing the height of the iframe to the bottom of the button was ingenious!
> > Just have a few suggestions to help tidy up the code a bit slightly_smiling_face
> 
> Thank you so much @elreydetoda! This is actually my first ever test (my day job does not have a good way to handle anything other than manual testing cry) so I will look over what you suggested and update this PR

That is so awesome! You did a really good job with it :grin: 

How was the experience overall? Still trying to get a feel on how people like using playwright and if it's approachable enough :sweat_smile:

2022-10-09 02:01 UTC, CGBassPlayer commented
I think the tool is great. I really based about 80% of the tests on things you did with the home page.

The docs were a little bit confusing to follow at first. But after a few reads, I was able to get through them alright.

Overall though, I think people will have an easy time working with this in the future.