Issue #521 Closes #521
JupiterBroadcasting/jupiterbroadcasting.com pull request #529
Opened 2023-03-18 19:11 UTC by 1701home

Merched the following files and then updated the show notes for each episode they were in. #521 
Closes #521

2023-03-18 20:06 UTC, CGBassPlayer requested changes
Overall looks good. Just a couple of small things:

1. The profile image for Cat is much higher resolution and should probably be used in the merged profile.
2. The now unused images should be deleted from the images directory to help keep the repo size to a minimum (`static/images/people`)

2023-03-18 20:56 UTC, CGBassPlayer commented
Don't forget about Jerome's duplicate image

2023-03-18 21:13 UTC, 1701home commented
I will get that removed and resubmitted

On Sat, Mar 18, 2023, at 3:56 PM, Ryan Goodwin - notifications at github.com wrote:
> 
> 
> Don't forget about Jerome's duplicate image
> 
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/pull/529#issuecomment-1474991575>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AQKXMNKZZNUFBV2VVOJAMGTW4YOPRANCNFSM6AAAAAAV7UIJYM>.
> You are receiving this because you authored the thread.Message ID: ***@***.***>
>

2023-03-18 21:23 UTC, CGBassPlayer approved these changes
This LGTM.

Here are new merged people:
---
The new https://www.jupiterbroadcasting.com/guests/catherine-kretzschmar/

![image](https://user-images.githubusercontent.com/34293941/226138573-b676f57e-abd9-4dd9-856b-f6825bf421b8.png)
![image](https://user-images.githubusercontent.com/34293941/226139136-4a2037a6-c97f-490b-bc58-6ac90c16ba2f.png)
---

The new https://www.jupiterbroadcasting.com/guests/jeromelaban/
![image](https://user-images.githubusercontent.com/34293941/226139160-27027864-769a-474f-bde4-8c1ff7da7fae.png)
![image](https://user-images.githubusercontent.com/34293941/226139182-36d71bf2-8c90-41f4-aee3-a5531c94e166.png)

2023-03-24 04:22 UTC, 1701home commented
Closes #512

2023-03-26 03:43 UTC, CGBassPlayer requested changes
Looks like the jlaban pictures were "undeleted" and the contributing is still here. If you need help getting this fixed up, feel free to reach out. Otherwise, just revert the contributing changes, then delete the images for jlaban

2023-03-26 03:43 UTC, CGBassPlayer commented on docs/CONTRIBUTING.md
So it looks like this file is still here even after our chat the other day. I would try the git revert again, but I did forget 1 important thing about it. It needs to be `git revert <commit-hash>..HEAD` to get all the changes undone. [source](https://stackoverflow.com/a/8561889/13417053)

Shoot me a message if you need help with this.

2023-03-26 04:06 UTC, 1701home commented on docs/CONTRIBUTING.md
> So it looks like this file is still here even after our chat the other day. I would try the git revert again, but I did forget 1 important thing about it. It needs to be `git revert <commit-hash>..HEAD` to get all the changes undone. [source](https://stackoverflow.com/a/8561889/13417053)
> 
> Shoot me a message if you need help with this.

I understand. I will perform the outline steps and message you with any questions.

2023-03-26 16:23 UTC, closed without merging

2023-03-26 16:29 UTC, 1701home commented
I will make a new PR to close #521 via a new branch.