Set metadata properly for hosts and guests
JupiterBroadcasting/jupiterbroadcasting.com pull request #544
Opened 2023-06-26 12:40 UTC by FryDay

Because people are setup as taxonomies, a little more work needs to be done in order to properly set the page metadata.

Fixes #520

2023-06-29 01:49 UTC, CGBassPlayer requested changes
First off: Thank you for contributing to the project! :tada: 

When testing this locally, I can see that the title listing the main [hosts](https://www.jupiterbroadcasting.com/hosts/) and [guests](https://www.jupiterbroadcasting.com/guests/) are 
`%!s(<nil>) | Jupiter Broadcasting`

![image](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/assets/34293941/6f77bcfe-b5a3-4b32-94b2-89482415aff4)

![image](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/assets/34293941/8d30482e-61f9-4cb5-a895-ec0b8e3cdc2e)

My best guess would be that you have to update your if condition to only check actual host and guest pages vs the main lists. Not sure how exactly that would look since I have not been in the code recently.

2023-06-30 02:36 UTC, CGBassPlayer approved these changes
Much better!

![image](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/assets/34293941/4bc3e136-cf33-455b-b74f-2f7e7828552f)

![image](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/assets/34293941/c3b19db5-2f1f-493a-a425-d93d72fe5267)

Screenshots showing names in the tab title
![image](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/assets/34293941/6b98cf0d-35ba-4d09-9a56-9da3b4212a90)

![image](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/assets/34293941/6e0e1fec-3fdf-480e-96bb-55e8b320e429)

Thank you again for this! @FryDay

2023-06-30 02:43 UTC, FryDay commented
> Thank you again for this! @FryDay

No problem! I've been a religious listener to every JB podcast since 2011. Figure it's about time I give back. I'm sure this won't be my last contribution 😄

2023-06-30 02:52 UTC, CGBassPlayer commented
I know the E2E test failed. Something weird is going on with the iframe loading times in the testing and that is causing the test to fail. I will merge this and hopefully look into the soon

2023-06-30 02:52 UTC, merged