Page People, filter is_archived hosts, mobile improvements
JupiterBroadcasting/jupiterbroadcasting.com pull request #563
Opened 2023-09-07 04:19 UTC by ChanceM

Resolves #262 
Resolves #92 

- Adds filtering for is_archived
- Pages guests on People Page
- Add mobile rendering improvements

2023-09-07 04:28 UTC, ChanceM commented
JupiterBroadcasting/show-scraper#41 should be merged along with this PR to prevent data being overwritten by the scraper.

2024-01-06 06:17 UTC, CGBassPlayer requested changes
Loving the improvements!

Only question I have is, should we add the archived flags to [Joe](https://www.jupiterbroadcasting.com/hosts/joe)
 and [Drew](https://www.jupiterbroadcasting.com/hosts/drew-devore)? Joe's last show was Dec 2020 and Drews was Mar 2020. I would be fine with leaving Drew active as he still edits for the shows, but just want to throw that out here since we are cleaning up the page.

2024-01-06 06:17 UTC, CGBassPlayer commented on themes/jb/layouts/partials/people/horizontal.html
> +    <div class="column is-one-third pr-0 px-0 pt-0 pb-1 columns mb-0">
`px-0` should cover what `pr-0` is doing
```suggestion
    <div class="column is-one-third px-0 pt-0 pb-1 columns mb-0">
```

2024-01-14 20:41 UTC, CGBassPlayer approved these changes
LGTM

2024-01-14 20:41 UTC, merged