Feature/add cr episodes 0 54
JupiterBroadcasting/jupiterbroadcasting.com pull request #568
Opened 2023-09-14 05:17 UTC by ChanceM

Resolves #222 

Add content for episodes and add image (EP 38).
If podcast_file is None try to play direct files.

2023-09-18 20:48 UTC, reclaimingmytime commented on content/show/coder-radio/0000.md
> +  "podcast_ogg_file": "https://traffic.libsyn.com/jnite/thedust-ogg.ogg",
This link doesn't point to a file anymore, including anything with `libsyn.com/jnite` (Jupiter@Nite, the old JB show?)

2023-09-18 20:52 UTC, reclaimingmytime commented on content/show/coder-radio/0000.md
> +  "video_file": "https://201206.jb-dl.cdn.scaleengine.net/coderradio/2012/thedust-432p.mp4",
All `scaleengine.net` links from this PR are also not accessible.

2023-09-18 20:54 UTC, reclaimingmytime commented
To to make the old episodes accessible, we would have to re-host the old episodes on a different server. This is part of issue #154, along with all the other unmigrated JB shows.

2023-09-19 03:19 UTC, ChanceM commented
> To to make the old episodes accessible, we would have to re-host them on a different server. This is part of issue #154, along with all the other unmigrated JB shows.

Yes, my goal here was to mainly add back content to an active show and to keep it as close to the original content as possible. For that matter JB could rip the audio and add them all back to fireside.

2024-01-07 00:15 UTC, CGBassPlayer requested changes
First of all. This is really impressive and is greatly appreciated. I am not sure how you got all the early coder episodes, but I love that you did! :slightly_smiling_face:  

I do think that the `Show Notes` title or the `Episode Links` title in the markdown needs be removed. Having both does not look that good.
![image](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/assets/34293941/6169edb1-a9b1-4b71-bace-a9119f31c994)

The other issue I saw when testing the page is that the tags title still appears even when there is no tags. I already have code ready to fix this (just a quick conditional in the template)  so no need to worry about that.

Last thing @reclaimingmytime had already pointed out being the the links that are dead. Not sure where their new location is but we should probably ask JB if they still have them hosted somewhere.

2024-01-07 00:15 UTC, CGBassPlayer commented on content/show/coder-radio/0001.md
> +#### What is Coder Radio?
For Episodes that have both `Show Notes` and `Episode Links`, one should be removed so we don't have multiple titles for the same content.

2024-01-14 21:39 UTC, CGBassPlayer approved these changes
I think I can live with some of the links being dead for now. I think what we have now will be good enough for the time being and we can address the 404 links when the archive site starts.

2024-01-14 21:39 UTC, merged